# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tit < Formula
  desc "a Git-Like CLI creating tutorials"
  homepage ""
  version "1.0.0-alpha-2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Creaft-JP/tit/releases/download/v1.0.0-alpha-2/tit_Darwin_x86_64.tar.gz"
      sha256 "b4921ddaf9a67bacc353ada3ea53acc35362be6dc2140f15cdd1fdd17de59ee5"

      def install
        bin.install "tit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Creaft-JP/tit/releases/download/v1.0.0-alpha-2/tit_Darwin_arm64.tar.gz"
      sha256 "1cc2fa06b26afda45ad9572e606bd4451c873252a048975a5602a4d03dcdf348"

      def install
        bin.install "tit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Creaft-JP/tit/releases/download/v1.0.0-alpha-2/tit_Linux_arm64.tar.gz"
      sha256 "5dd50f5d326421e271f0c941b5f758e88a3f0ef1674c0fc7242621e9042d3ba9"

      def install
        bin.install "tit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Creaft-JP/tit/releases/download/v1.0.0-alpha-2/tit_Linux_x86_64.tar.gz"
      sha256 "e9a70fca55b1f90a953a337214a4279118f6f6292371e191a144ff7cb0c14e9d"

      def install
        bin.install "tit"
      end
    end
  end
end
