# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tut < Formula
  desc "a Git-Like CLI creating tutrials"
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Creaft-JP/tut/releases/download/v0.2.0/tut_Darwin_arm64.tar.gz"
      sha256 "f6f4aa055dccff87d8ba592fe289f1071845112f781b5747f09020a27e222f27"

      def install
        bin.install "tut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Creaft-JP/tut/releases/download/v0.2.0/tut_Darwin_x86_64.tar.gz"
      sha256 "0a595d1d1d66fcbad8042cd44a08ba7094bb31365757a173f2874d0673547285"

      def install
        bin.install "tut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Creaft-JP/tut/releases/download/v0.2.0/tut_Linux_x86_64.tar.gz"
      sha256 "5f807cb45b3829e98c2196eea0692cf569684b2758abdad446dae7623a5311ff"

      def install
        bin.install "tut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Creaft-JP/tut/releases/download/v0.2.0/tut_Linux_arm64.tar.gz"
      sha256 "444137b2c03cb3f92d398d013ca3a95316a3358014cd78559ae1fa3928932930"

      def install
        bin.install "tut"
      end
    end
  end
end
